Fix/tr 199 flat radio navigation
oat-sa/tao-test-runner-qti-fe pull request #358
Opened 2021-02-22 08:12 UTC by lecosson

2021-02-22 12:49 UTC, btamas requested changes

2021-02-22 12:49 UTC, btamas commented on package.json
> +    "version": "2.18.8",
Version bump is not necessary.

2021-02-24 10:24 UTC, btamas requested changes
The `itemNavigation.js` is not loaded on my side, so it takes no effect.

2021-02-24 12:06 UTC, btamas approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-02-24 14:12 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-02-24 14:14 UTC, jsconan commented
Units test for regarding the keyNavigation are passing successfully. However, there is something preventing the full test suite to complete. But it is not related to this PR.

2021-02-24 15:16 UTC, meefox approved these changes

2021-02-24 15:22 UTC, merged