fix: TR-1206 disallow reload page on opened error popup
oat-sa/tao-test-runner-qti-fe pull request #385
Opened 2021-05-19 12:37 UTC by lecosson

**Related to:** https://oat-sa.atlassian.net/browse/TR-<ID>

**Changes:**
- flag saved to test runner state for prevent suddenly page reload on errors

**How to check:**
- see compagnion PR description

**Requires:**
 - [ ] https://github.com/oat-sa/<EXT>/pull/<PR>

2021-05-20 07:48 UTC, marpesia commented
It works fine, and the code looks good to me.

Two questions:
- There is an issue with the continuous integration. Is that a problem?
- And I've read the expected result, and I'm wondering if they want to leave the test-taker the ability to click pause bottom themselves... I mean, the pause button is being disabled on the offline scenario right now, and I'm not sure if that is ok. Did you check that with QA?
```
Expected result:
Pop up is displayed on screen, test-taker can either reload the page or pause the test by clicking corresponding buttons
```

2021-05-20 08:00 UTC, marpesia approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-20 13:40 UTC, jsconan requested changes
As explained on the other PR, while the proposed solution looks to work, it is no correct.

The proper solution would be at the error handler layer. In fact, since this plugin is working on the error event, it should also qualify the error and prevent further action if it is processed by this plugin.

The page redirection is made there when an error occurs if this is a 403 or a 500: https://github.com/oat-sa/extension-tao-testqti/blob/e006c93fb17b1e539787f2decfbcb796122eda64/views/js/controller/runner/runner.js#L160:L163

What you can do is to check if the error is a 500, then prevent the error to move forward.

As a suggestion, you could do the following:

- Hard rejection of the error (but this will prevent further logging):
```javascript
        const processError = err => {
            testRunner
                .on('reloadpage', () => window.location.reload())
                .trigger('disablenav disabletools hidenav')
                .trigger(`confirm.${name}`, dialogTpl(dialogMessage), returnToHome, reloadPage, dialogConfig);
            if (err.code === 500) {
                return Promise.reject();
            }
        };

        testRunner.before('error', (e, err) => processError(err));
```
- Impersonation of the error to prevent the exit (better for further actions to take place but the exit):
```javascript
        const processError = err => {
            testRunner
                .on('reloadpage', () => window.location.reload())
                .trigger('disablenav disabletools hidenav')
                .trigger(`confirm.${name}`, dialogTpl(dialogMessage), returnToHome, reloadPage, dialogConfig);
            if (err.code === 500) {
                err.originalCode = err.code;
                delete err.code;
            }
        };

        testRunner.before('error', (e, err) => processError(err));
```

2021-05-20 14:50 UTC, lecosson commented
@marpesia sorry for re-request, implementation was changed

2021-05-21 05:33 UTC, marpesia commented
But now I can see an error on test-taker screen after push the 'next' button on the 500 error. Do you see the same on Chrome?
![image](https://user-images.githubusercontent.com/11692751/119086802-53986b00-ba06-11eb-92cb-717f4bbfe7a3.png)

On Browser console
![image](https://user-images.githubusercontent.com/11692751/119087024-b0942100-ba06-11eb-8df1-9526a1e76054.png)

2021-05-21 06:26 UTC, marpesia requested changes
Please confirm my error :)

2021-05-21 06:51 UTC, jsconan requested changes
Works wells.
However, the PR description is not accurate anymore and should be changed.
And the unit tests are failing and needs an update:
```
test/plugins/controls/connectivity/pauseOnError/test.html
  pauseOnError plugin
    error then reload
      Too many calls to the `assert.async` callback
          at http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
          at http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:245:15
          at Function.forEach (http://127.0.0.1:59668/node_modules/lodash/lodash.js:3656:15)
          at Object.trigger (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:226:13)
      Expected 6 assertions, but 12 were run
          at http://127.0.0.1:59668/test/plugins/controls/connectivity/pauseOnError/test.js:79:11
          at Object.execCb (http://127.0.0.1:59668/environment/require.js:1696:33)
          at Module.check (http://127.0.0.1:59668/environment/require.js:883:51)
          at Module.<anonymous> (http://127.0.0.1:59668/environment/require.js:1139:34)
          at http://127.0.0.1:59668/environment/require.js:134:23
          at http://127.0.0.1:59668/environment/require.js:1189:21
          at each (http://127.0.0.1:59668/environment/require.js:59:31)
          at Module.emit (http://127.0.0.1:59668/environment/require.js:1188:17)
    error then pause
      Too many calls to the `assert.async` callback
          at http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
          at http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:245:15
          at Function.forEach (http://127.0.0.1:59668/node_modules/lodash/lodash.js:3656:15)
          at Object.trigger (http://127.0.0.1:59668/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:226:13)
      Expected 6 assertions, but 12 were run
          at http://127.0.0.1:59668/test/plugins/controls/connectivity/pauseOnError/test.js:110:11
          at Object.execCb (http://127.0.0.1:59668/environment/require.js:1696:33)
          at Module.check (http://127.0.0.1:59668/environment/require.js:883:51)
          at Module.<anonymous> (http://127.0.0.1:59668/environment/require.js:1139:34)
          at http://127.0.0.1:59668/environment/require.js:134:23
          at http://127.0.0.1:59668/environment/require.js:1189:21
          at each (http://127.0.0.1:59668/environment/require.js:59:31)
          at Module.emit (http://127.0.0.1:59668/environment/require.js:1188:17)
```

Hint: look at the way the [error is simulated](https://github.com/oat-sa/tao-test-runner-qti-fe/blob/f846416b62afc7e1337c9ea64d82c7650e4265a6/test/plugins/controls/connectivity/pauseOnError/test.js#L87) in the unit tests.

You can fix this by supplying an error object: `runner.trigger('error', new Error('test'));`

2021-05-21 06:51 UTC, jsconan commented on src/plugins/controls/connectivity/pauseOnError.js
> +        const processError = (error) => {
**chore:** The coding style convention says: no parenthesis around single parameters for arrow functions

2021-05-21 06:55 UTC, jsconan commented
> But now I can see an error on test-taker screen after push the 'next' button on the 500 error. Do you see the same on Chrome?

Yes, this is the purpose of letting the error goes up to the logging process ;). The logged event can be sent to the backend if the layer is configured. Otherwise they will only show up in the console. If we simply prevent the error to be notified, then we would have to no chance to notify the server and log it, and then the admin will never see there was some issue on the client app.

Eventually, we might do something to prevent the redish message to appear. But let's see if this is ok for the customer and from the UX.

2021-05-21 07:37 UTC, btamas commented
> Works wells.
> However, the PR description is not accurate anymore and should be changed.
> And the unit tests are failing and needs an update:

Same result. BTW, is it still a Draft PR?

2021-05-21 07:37 UTC, btamas requested changes
Tests should be fixed.

2021-05-21 08:09 UTC, lecosson commented
> Tests should be fixed.

2021-05-21 08:11 UTC, btamas commented
> Tests should be fixed.

Confirmed

2021-05-21 08:11 UTC, btamas approved these changes
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-21 08:18 UTC, marpesia approved these changes
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-21 08:57 UTC, jsconan approved these changes
All good!

**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-21 08:58 UTC, merged