fix/tr-888/right-to-left-review-panel
oat-sa/tao-test-runner-qti-fe pull request #399
Opened 2021-06-08 06:27 UTC by marpesia

Related to TR-888

To test it:

Run as guest with according locale in generis.conf.php: define('DEFAULT_ANONYMOUS_INTERFACE_LANG','ar-arb'); at line 47

2021-06-08 09:27 UTC, btamas approved these changes

2021-06-08 09:27 UTC, btamas commented
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-08 16:49 UTC, meefox requested changes

2021-06-08 16:49 UTC, meefox commented on scss/inc/rtl/_review-panel.scss
> +                    .qti-navigator-counter {
It is not necessary to have specificity for those classes 0.10.1 = 0.2.1 (_rtl.scss) + 0.8.0 (_review-panel.scss)
![Screenshot 2021-06-08 at 18 41 57](https://user-images.githubusercontent.com/2067027/121225222-98872300-c889-11eb-89c8-72dc4f008ac2.png)
I woud suggest to keep it lower as much is possible.

Or is there is a reason for this?

2021-06-09 14:33 UTC, jsconan approved these changes
Looks ok.

![image](https://user-images.githubusercontent.com/1500098/121374501-3a694700-c940-11eb-9b65-8c879a49892a.png)

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-10 10:49 UTC, lecosson approved these changes

2021-06-10 10:51 UTC, meefox approved these changes
All good, thanks for fixing this.
![Screenshot 2021-06-10 at 12 49 18](https://user-images.githubusercontent.com/2067027/121512858-7953d700-c9ea-11eb-8593-3887fd2911fb.png)

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-17 09:15 UTC, merged