fix: TR-857 swap title bar margins for RTL languages
oat-sa/tao-test-runner-qti-fe pull request #400
Opened 2021-06-08 13:05 UTC by lecosson

**Related to:** https://oat-sa.atlassian.net/browse/TR-857

**Changes:**
- changed margins (swapped left-right) for title bar elements: `connectivity-box` and `progress-box`

**How to check:**
- run delivery with enabled RTL language

**Requires:**
 - [ ] https://github.com/oat-sa/<EXT>/pull/<PR>

2021-06-09 07:03 UTC, marpesia approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x]  Commits messages are meaningful
- [ ]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-09 16:18 UTC, meefox commented on scss/inc/rtl/_title-bar.scss
> +          & > * {
well, is possible to avoid '*' ?

2021-06-10 06:58 UTC, jsconan requested changes
The change is ok regarding the connectivity message and the progress box. However, the timer is not properly displayed in RTL.

Compare:
![image](https://user-images.githubusercontent.com/1500098/121478223-156ce680-c9c9-11eb-966d-84c9b306bcbc.png)
![image](https://user-images.githubusercontent.com/1500098/121478377-40573a80-c9c9-11eb-99b2-8f9c8136d2d9.png)

2021-06-11 11:14 UTC, lecosson commented on scss/inc/rtl/_title-bar.scss
> +          & > * {
changed

2021-06-14 07:04 UTC, jsconan approved these changes
It looks ok.

- RTL: ![image](https://user-images.githubusercontent.com/1500098/121849694-f5e8fd00-cceb-11eb-90e0-3e5548367c6d.png)
- LTR: ![image](https://user-images.githubusercontent.com/1500098/121849713-000afb80-ccec-11eb-81d3-1aebbc7610f7.png)

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-17 12:39 UTC, merged