Feature TR-886 Right-to-left Test Runner item validation messages
oat-sa/tao-test-runner-qti-fe pull request #406
Opened 2021-06-15 14:42 UTC by marpesia

**Related to:** [TR-886](https://oat-sa.atlassian.net/browse/TR-886)

**Description:**
Change direction of item validation message

**Changes:**
- Add scss file with RTL changes to feedback messages

**How to check:**
- Add choice item with a min allowed choices
- Change language to ar-arb

**Requires:**
- None

2021-06-16 08:14 UTC, jsconan requested changes
The icon is indeed aligned on the opposite side. But this text is kept in LTR.

![image](https://user-images.githubusercontent.com/1500098/122177321-ca017f00-ce85-11eb-977c-a7d5079277f5.png)

**Thought:** this relies on the parent `dir` attribute. For the time being, only the page has one since we implemented it for the test runner. But we'll also have additional layers, especially at the item level. So maybe do we need to enforce the direction in every validation messages

2021-06-17 09:40 UTC, jsconan reviewed
It looks ok for the icon.
It also looks ok for the text, but only for the time being since the language direction is not changed at the item level. However, it won't work anymore when the language direction will be applied ate the item level.

Look at this PoC: 
![image](https://user-images.githubusercontent.com/1500098/122372176-c131ab80-cf60-11eb-86d4-95b44992c373.png)

2021-06-17 15:16 UTC, jsconan approved these changes
Good job!

Works well even if the item is set in a different direction.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-18 09:33 UTC, lecosson approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-22 09:45 UTC, merged