Force Safari iOS to reconsider the scroll styling
oat-sa/tao-test-runner-qti-fe pull request #469
Opened 2022-02-22 16:57 UTC by krampstudio

Related to https://oat-sa.atlassian.net/browse/TR-3071

 - After an item renders on Safari iOS, the scrollable elements may not be actually scrollable (a Safari bug), so we force it to reconsider adding the scroll. This seems to be the same issue as [this one](https://stackoverflow.com/questions/28288710/cant-scroll-inside-a-div-after-applying-webkit-transform-in-safari), because it occurs only after a form having the focus AND the loading bar to animate :confused: 

Requires: 
 - [ ] https://github.com/oat-sa/tao-core-sdk-fe/pull/130/files

How to test
 - run unit tests (the keyNavigation tests were already failing :unamused: )
 - along with the other PRs or on TAE by running the failing test on iOS

2022-02-25 08:27 UTC, yukipastelcat approved these changes
Codewise everything looks good, can confirm, that following solution works (tested with Simulator).

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-02-25 08:27 UTC, yukipastelcat commented on src/provider/qti.js
> +                    if (browser.isIOs()) {
iOS spelling there is a bit weird, at first I thought about inputs/outputs🤔

2022-02-25 09:51 UTC, shaveko requested changes
I've tested on iPad emulator and real iPhone

I'm facing the following issue, which is not critical, but still degrates user experience.

If you navigate and start scrolling while item is being loaded, the scrolling doesn't happen afterwards. Sometimes you wait for a while and content bacomes scrollable again, 

Please check the video attached


https://user-images.githubusercontent.com/10635482/155693723-bd174208-9166-422b-85a4-03043e24415c.mp4

2022-02-25 16:55 UTC, krampstudio commented
@shaveko as agreed we will treat this issue separately, thanks for reporting

2022-02-28 13:04 UTC, shaveko approved these changes
The issue I found is floating one and doen't happen every time. Also, check the comment to original issue https://oat-sa.atlassian.net/browse/TR-3071?focusedCommentId=174372

We are considering the issue is on Safari side and cannot be worked around by our fix

2022-03-01 07:41 UTC, merged