Feature/TR 3449/fizzy review panel item tooltip
oat-sa/tao-test-runner-qti-fe pull request #472
Opened 2022-03-10 14:33 UTC by olga-kulish

Related to https://oat-sa.atlassian.net/browse/TR-3449

- [ ] apply https://github.com/oat-sa/tao-core-ui-fe/pull/442

2022-03-11 13:37 UTC, oatymart requested changes

2022-03-15 07:53 UTC, jsconan commented on package.json
>          "@oat-sa/tao-core-sdk": "1.17.0",
The [PR](https://github.com/oat-sa/tao-test-runner-qti-fe/pull/473) has been merged. It should be fixed with `develop` merged

2022-03-15 08:28 UTC, jsconan approved these changes
Looks good.

**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- ~~[ ] New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2022-03-15 08:33 UTC, oatymart approved these changes
All good now! LGTM

- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Documentation is updated according to changes (if applicable)

2022-03-18 08:53 UTC, merged